version: '3.4'
name: minimalapi_container
services:
  minimalapi:
    container_name: minimalapi
    image: ${DOCKER_REGISTRY-}minimalapi
    build:
      context: .
      dockerfile: MinimalAPI/Dockerfile
    depends_on:
      - sqlserver
  sqlserver:
    container_name: sqlserver
    image: mcr.microsoft.com/mssql/server:2022-latest
    hostname: 'sqlserver'
    environment:
      ACCEPT_EULA: 'Y'
      SA_PASSWORD: "yourStrong(!)Password"
    ports:
      - '1433:1433'    
    expose:
      - 1433